# Generated by Django 2.0 on 2018-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liba', '0002_auto_20180416_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.DateField(),
        ),
    ]
