# Generated by Django 2.0 on 2018-04-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liba', '0003_auto_20180416_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_id',
            field=models.ManyToManyField(default=None, to='liba.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(),
        ),
    ]
