# Generated by Django 2.0 on 2018-04-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liba', '0004_auto_20180416_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liba.Genre'),
        ),
    ]
