# Generated by Django 2.0 on 2018-04-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liba', '0005_auto_20180417_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liba.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_id',
            field=models.ManyToManyField(default=None, related_name='books', to='liba.Author'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='author_id',
            field=models.ManyToManyField(related_name='publishers', to='liba.Author'),
        ),
    ]
