# Generated by Django 2.0 on 2018-04-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liba', '0007_auto_20180418_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulation',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulation', to='liba.Book'),
        ),
    ]
