# Generated by Django 2.0 on 2018-04-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liba', '0008_auto_20180418_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='liba.Publisher'),
        ),
    ]
